# See: https://www.dartlang.org/tools/pub/pubspec
name: flutter_sqlcipher
version: 0.4.4
description: >-
  Flutter plugin for SQLCipher, an extension to SQLite that provides
  transparent AES encryption of database files.
author: Arto Bendiken <arto@bendiken.net>
homepage: https://github.com/drydart/flutter_sqlcipher
documentation:
dependencies:
  flutter:
    sdk: flutter
  flutter_android:
    git:
      url: https://github.com/HuginTech/flutter_android.git
  meta: ^1.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: '>=1.3.4 <2.0.0'
dependency_overrides:
environment:
  sdk: '>=2.1.0 <3.0.0'
executables:
flutter:
  plugin:
    androidPackage: com.github.drydart.flutter_sqlcipher
    pluginClass: FlutterSQLCipherPlugin
